// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs winmail-viewer`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "eml-viewer",
    "icon": "📧",
    "name": {
      "en": "EML Viewer",
      "ja": "EML ビューア",
      "zh": "EML 查看器",
      "de": "EML-Viewer",
      "es": "Visor de EML"
    },
    "desc": {
      "en": "Open a saved .eml email and read it in your browser.",
      "ja": ".eml メールファイルをブラウザで開いて読みます。",
      "zh": "在浏览器中打开并阅读 .eml 邮件文件。",
      "de": "Öffne eine gespeicherte .eml-E-Mail und lies sie im Browser.",
      "es": "Abre un correo .eml guardado y léelo en tu navegador."
    }
  },
  {
    "slug": "zip-viewer",
    "icon": "👁️",
    "name": {
      "en": "ZIP Viewer",
      "ja": "ZIPの中身を確認",
      "zh": "查看 ZIP",
      "de": "ZIP-Viewer",
      "es": "Visor de ZIP"
    },
    "desc": {
      "en": "See what's inside a .zip without extracting it.",
      "ja": "展開せずに.zipの中身を確認します。",
      "zh": "不解压也能看 .zip 里面有什么。",
      "de": "Schau in ein .zip hinein, ohne es zu entpacken.",
      "es": "Ve qué contiene un .zip sin extraerlo."
    }
  },
  {
    "slug": "hex-viewer",
    "icon": "🔍",
    "name": {
      "en": "Hex Viewer",
      "ja": "Hex Viewer",
      "zh": "Hex Viewer",
      "de": "Hex Viewer",
      "es": "Hex Viewer"
    },
    "desc": {
      "en": "Inspect any file as a hex dump, right in your browser.",
      "ja": "どんなファイルもブラウザで 16 進ダンプとして表示。",
      "zh": "在浏览器中把任意文件显示为十六进制内容。",
      "de": "Beliebige Dateien im Browser als Hex-Dump ansehen.",
      "es": "Ver cualquier archivo como volcado hexadecimal en tu navegador."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'winmail-viewer';
